set -g mouse on
set -g status-left-length 30

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ステータスラインの色をホスト名で切り替え
if-shell '[ "$(hostname)" = "EDOPC-087.local" ]' \
  'set -g status-style "bg=#1e2e74,fg=#7b88a1"; \
   set -g status-left-style "bg=#1e2e74,fg=#7b88a1"; \
   set -g status-right-style "bg=#1e2e74,fg=#7b88a1"; \
   set -g window-status-style "bg=#1e2e74,fg=#7b88a1"; \
   set -g window-status-current-style "bg=#1e2e74,fg=#89b4fa,bold"; \
   set -g message-style "bg=#1e2e74,fg=#cdd6f4"; \
   set -g status-left " [#S] EDOCODE "; \
   set -g window-status-format ""; \
   set -g window-status-current-format ""; \
   set -g status-right " %Y/%m/%d %H:%M "'

if-shell '[ "$(hostname)" = "YMD-MacBook-Air.local" ]' \
  'set -g status-style "bg=#741e1e,fg=#a17b7b"; \
   set -g status-left-style "bg=#741e1e,fg=#a17b7b"; \
   set -g status-right-style "bg=#741e1e,fg=#a17b7b"; \
   set -g window-status-style "bg=#741e1e,fg=#a17b7b"; \
   set -g window-status-current-style "bg=#741e1e,fg=#fa8989,bold"; \
   set -g message-style "bg=#741e1e,fg=#f4cdcd"; \
   set -g status-left " [#S] YMD "; \
   set -g window-status-format ""; \
   set -g window-status-current-format ""; \
   set -g status-right " %Y/%m/%d %H:%M "'
