"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#d2a3a3)\
[  ](bg:#d2a3a3 fg:#090c0c)\
[](bg:#f07676 fg:#d2a3a3)\
$directory\
[](fg:#f07676 bg:#603939)\
$git_branch\
$git_status\
[](fg:#603939 bg:#362121)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#362121 bg:#301d1d)\
[ HOME ](#666666)\
$time\
[ ](fg:#301d1d)\
\n$character"""

[directory]
style = "fg:#2b2b2b bg:#f07676"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#603939"
format = '[[ $symbol $branch ](fg:#f07676 bg:#603939)]($style)'

[git_status]
style = "bg:#603939"
format = '[[($all_status$ahead_behind )](fg:#f07676 bg:#603939)]($style)'

[nodejs]
symbol = ""
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07676 bg:#362121)]($style)'

[rust]
symbol = ""
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07676 bg:#362121)]($style)'

[golang]
symbol = ""
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07676 bg:#362121)]($style)'

[php]
symbol = ""
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07676 bg:#362121)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#301d1d"
format = '[[  $time ](fg:#cba0a0 bg:#301d1d)]($style)'
